# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  dhcpd1:
    :hostname: "dhcpd1"
    :ip: "192.168.35.100"
    :ram: 512
    :cpu: 1
    :box: "debian/stretch64"

:groups:
  dhcpd1:
    - dhcpd1
  dhcpd:
    - dhcpd1
  dhcpd_servers:
    - dhcpd1
