---

- name: Restart dhcp server
  service:
    name: '{{ item }}'
    state: 'restarted'
  with_items: "{{ boss__dhcpd__services.server }}"

- name: Restart dhcp relay
  service:
    name: '{{ item }}'
    state: 'restarted'
  with_items: "{{ boss__dhcpd__services.relay }}"

- name: Restart dhcp probe
  service:
    name: '{{ item }}'
    state: 'stopped'
  with_items: "{{ boss__dhcpd__services.probe }}"
  notify: [ 'Start dhcp probe' ]

- name: Start dhcp probe
  service:
    name: '{{ item }}'
    state: 'started'
  with_items: "{{ boss__dhcpd__services.probe }}"

# vim: set ts=2 sw=2:
